config/routes.rb
Rails.application.routes.draw do

  root 'welcome#show'
  get '/resume', to: 'resume#show'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def show
    render 'layouts/application.html.erb'
  end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController

  def show
    render 'show.html.erb'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  # stylesheet_link_tag "assets/stylesheets/welcome.css"

  def show
    render 'show.html.erb'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="icon"
      type="image/png"
      href="../../assets/images/favicon.png" />
      
  <title>AT</title>
  <link href='https://fonts.googleapis.com/css?family=Oxygen:700,400,300' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "application" %>

</head>
<body>

  <div class="main">
    <%= yield %>
  </div>


</body>
</html>

app/views/resume/show.html.erb
<%= stylesheet_link_tag "resume" %>

<div class='resume-wrapper'>

  <h1>Alison Tague</h1>
  <h6>Full-Stack Ruby on Rails and JavaScript Engineer</h6>

  <div class="main-section">
    <div class='jobs-and-descriptions'>
      <h2 class='section'>Experience</h2>
      <h3 class='company'>Company</h3>
      <h3 class='position'>Job Title</h3>
      <h4 class='city'>City</h4>
      <p class='date'>date</p>
      <p class='description'></p>
    </div>

    <div class='education-information'>
      <h2 class='section'>Education</h2>
      <h3 class='school'>General Assembly, <span class='focus'>WDI</span><span class='separator'></span><span class='city'>Washington, D.C.</span></h3>
      <p class='description'>Student, Full-Time Web Development Immersive, 2015</p>

      <h3 class='school'>Boston University, <span class='focus'>School of Hospitality</span><span class='separator'></span><span class='city'>Boston, MA</span></h3>
      <p class='description'>Bachelor of Science, 2011</p>
    </div>
  </div>

  <div class='listed-skills-technologies'>
    <h1 class='list-header'>Languages</h1>
      <ul>
        <li>Ruby</li>
        <li>Javascript</li>
        <li>SQL</li>
        <li>CSS/SASS</li>
      </ul>
    <h1 class='list-header'>Libraries/Frameworks</h1>
      <ul>
        <li>Rails</li>
        <li>Sinatra</li>
        <li>rSpec</li>
        <li>Jasmine</li>
        <li>jQuery</li>
        <li>Underscore.js</li>
        <li>Bootstrap</li>
        <li>MiniTest</li>
      </ul>
    <h1 class='list-header'>Methodologies</h1>
      <ul>
        <li>REST</li>
        <li>MVC</li>
        <li>TDD</li>
        <li>OOP</li>
        <li>Agile</li>
      </ul>
    <h1 class='list-header'>SKILLS</h1>
      <ul>
        <li>HTML</li>
        <li>API Integration</li>
        <li>Git</li>
        <li>PostgreSQL</li>
        <li>JIRA</li>
      </ul>
  </div>
  <div class='bottom'></div>

</div>




<%= render partial: './footer' %>

app/views/welcome/_welcome_footer.html.erb
<div class='footer'>
  <p>View my source code <a href='https://github.com/alisonmtague/portfolio'>here</a>.</p>
</div>

app/views/welcome/show.html.erb
<%= stylesheet_link_tag "welcome" %>

<div class='portfolio-welcome-page'>
  <%= image_tag("AT.png", class: 'image', size: "200")%>
  <div class='name-and-about'>
    <h1 class='name'>ALISON TAGUE</h1>
    <p class='about'>I am a Full Stack Javascript and Ruby Developer.
      I like building out the front end while improving my skills with Rails.</p>
  </div>
  <div class='social-links'>

    <%= link_to "Look at my resume", resume_path, class: 'resume' %>
    <a class='github' href='https://github.com/alisonmtague'><i class="fa fa-github"></i>Check out what I'm working on</a>
    <a class='linkedin' href='https://www.linkedin.com/in/alisontague'><i class="fa fa-linkedin-square"></i>View my LinkedIn</a>
    <a class='twitter' href='https://twitter.com/alisontague'><i class="fa fa-twitter"></i>Read my tweets</a>
    <a class='spotify' href='https://open.spotify.com/user/1261061223'><i class="fa fa-music"></i>See my music interests</a>

    <%= mail_to "alisonmtague@gmail.com", subject: "Hey Alison!" do %>
      <span class='email'><i class="fa fa-envelope-o"></i>Email me</span>
    <% end %>

  </div>
</div>

<%= render partial: 'welcome_footer' %>